version: '3.7'

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - './services/frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
